### ISSUE TITLE
gregtech.recipes disable Grog

### ISSUE THREAD

**Issue by leagris** [MightyPirates/OpenComputers#1577]
As gregtech.recipes disable Grog, it is impossible to get Grog without non existent Hot Wet Ocean biome to breed Scummy bees.

Either Grog recipe should be re-enabled or not a required ingredient of Nano-Machines.

Grog is also needed to wipe/reset eaten Nano-Machines.

I re-enabled Grog recipe as is in user.recipes:

``` YAML
# Re-Add Grog recipe as it is disabled by gregtech.recipes and a needed
# ingredient with no other mean of obtaining

acid {
  type: shapeless
  input: [bucketWater, sugar, slimeball, fermentedSpiderEye, bone]
}
```
