### ISSUE TITLE
Recipe conflict Diamond Shards

### ISSUE THREAD

**Issue by DarkGuardsman** [MightyPirates/OpenComputers#1852]
This was reported to me by another user on the server I play, but it looks like there is a recipe conflict with one of the diamond recipes. A potential solution could be to OreDictionary nuggets as an optional item in the recipes, instead of just shards.
![thing](https://cloud.githubusercontent.com/assets/1477330/15834418/6ffddea6-2bf9-11e6-87ac-6b494aa0c838.png)

**Comment by Vexatos** [comment]
@fnuecke cutting wire + diamond? :wink:

**Comment by jkirkpatrick** [comment]
Found a conflict with Agricraft (diamond nuggets from Diamahlia plant)... MC 1.7.10 / OC1.6.0-RC1 / Agricraft 1.5.0. Another option may be an additional crafting recipe e.g. 3 diamond chips from 4 diamond nuggets (1 chip == 1.333 nuggets).

Update: my issue is with Translocator, not Agricraft. For any other users who find this and need an immediate workaround, you can add the following to the bottom of the `config/opencomputers/user.recipes` file:

``` yaml
chipDiamond {
  shapeless: true
  input: ["minecraft:diamond", "minecraft:diamond"]
  output: 12
}
```

This preserves the 6:1 ratio, but unfortunately doubles then number of diamonds. Another option:

``` yaml
chipDiamond {
  shapeless: true
  input: ["minecraft:diamond", "minecraft:sand"]
  output: 6
}
```
